# Generated by Django 5.1.7 on 2025-11-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais_residencia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_internacional', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Editoriales y Proveedores',
                'ordering': ['nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_pedido', models.CharField(default='Pendiente', max_length=50)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_Biblia.clienteglobal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=50)),
                ('precio_base_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_Biblia.editorialproveedor')),
            ],
            options={
                'verbose_name_plural': 'Productos Globales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen_ubicacion', models.CharField(max_length=255)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('minimo_stock', models.PositiveIntegerField(default=0)),
                ('maximo_stock', models.PositiveIntegerField(default=100)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='app_Biblia.productosglobal')),
            ],
            options={
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_detalle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_item', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_linea', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Biblia.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Biblia.productosglobal')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedido',
                'ordering': ['pedido', 'numero_linea'],
            },
        ),
    ]
